### ISSUE TITLE
Uploaded file seems to have some issues

### ISSUE THREAD

**Issue by birm** [sharmalab/TCIAPubHubAdmin#15]
As a test, I added a file as a resource type, got errors:

Uncaught TypeError: Cannot read property 'replace' of undefined
Please report this to https://github.com/chjj/marked.
    at t.lex (http://172.20.6.65:13000/javascripts/browserify/one.entry.js:34:11916)
    at Function.t.lex (http://172.20.6.65:13000/javascripts/browserify/one.entry.js:34:11870)
    at p (http://172.20.6.65:13000/javascripts/browserify/one.entry.js:34:9863)
    at n.markdownToHTML (http://172.20.6.65:13000/javascripts/browserify/one.entry.js:1:3746)
    at http://172.20.6.65:13000/javascripts/browserify/one.entry.js:1:4794
    at Array.map (native)
    at n.render (http://172.20.6.65:13000/javascripts/browserify/one.entry.js:1:4249)
    at d._renderValidatedComponentWithoutOwnerOrContext (http://172.20.6.65:13000/javascripts/browserify/one.entry.js:16:29915)
    at d._renderValidatedComponent (http://172.20.6.65:13000/javascripts/browserify/one.entry.js:16:30091)
    at d.i [as _renderValidatedComponent] (http://172.20.6.65:13000/javascripts/browserify/one.entry.js:1:21586)

AND

Uncaught TypeError: Cannot read property 'text' of undefined
    at one.entry.js:1
    at f.callback (one.entry.js:20)
    at f.crossDomainError (one.entry.js:20)
    at XMLHttpRequest.n.onreadystatechange (one.entry.js:20)

**Comment by birm** [comment]
This may be because a markdown file is expected instead of pdf?

**Comment by lastlegion** [comment]
This was because of the assumption that Bindaas would be in the same machine/container as Pubhub. This is no longer the case in our current deployment. I've fixed this issue. Will test it again tomorrow and close this.
